<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\State;

class StateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $statiesRecords = [
            ['id'=>1,'country_id'=>1,'name'=>'وسط القاهرة'],
            ['id'=>2,'country_id'=>1,'name'=>'هليوبوليس الجديدة'],
            ['id'=>3,'country_id'=>1,'name'=>'مصر القديمة'],
            ['id'=>4,'country_id'=>1,'name'=>'مصر الجديدة'],
            ['id'=>5,'country_id'=>1,'name'=>'مدينتى'],
            ['id'=>6,'country_id'=>1,'name'=>'مدينة نصر'],
            ['id'=>7,'country_id'=>1,'name'=>'مدينة بدر'],
            ['id'=>8,'country_id'=>1,'name'=>'مدينة المستقبل'],
            ['id'=>9,'country_id'=>1,'name'=>'مدينةالشروق'],
            ['id'=>10,'country_id'=>1,'name'=>'مدينة السلام'],
            ['id'=>11,'country_id'=>1,'name'=>'مدينة 15 مايو'],
            ['id'=>12,'country_id'=>1,'name'=>'قصر النيل'],
            ['id'=>13,'country_id'=>1,'name'=>'عين شمس'],
            ['id'=>14,'country_id'=>1,'name'=>'عزبة النخل'],
            ['id'=>15,'country_id'=>1,'name'=>'طرة'],
            ['id'=>16,'country_id'=>1,'name'=>'شيراتون'],
            ['id'=>17,'country_id'=>1,'name'=>'شبرا'],
            ['id'=>18,'country_id'=>1,'name'=>'زهراء المعادى'],
            ['id'=>19,'country_id'=>1,'name'=>'روض الفرج'],
            ['id'=>20,'country_id'=>1,'name'=>'رمسيس وامتداد رمسيس'],
            ['id'=>21,'country_id'=>1,'name'=>'دار السلام'],
            ['id'=>22,'country_id'=>1,'name'=>'حلوان'],
            ['id'=>23,'country_id'=>1,'name'=>'حلمية الزيتون'],
            ['id'=>24,'country_id'=>1,'name'=>'حدائق حلوان'],
            ['id'=>25,'country_id'=>1,'name'=>'حدائق القبة'],
            ['id'=>26,'country_id'=>1,'name'=>'حدائق الزيتون'],
            ['id'=>27,'country_id'=>1,'name'=>'جسر السويس'],
            ['id'=>28,'country_id'=>1,'name'=>'جاردن سيتى'],
            ['id'=>29,'country_id'=>1,'name'=>'بولاق ابو العلا'],
            ['id'=>30,'country_id'=>1,'name'=>'باب الشعرية'],
            ['id'=>31,'country_id'=>1,'name'=>'الوايلى'],
            ['id'=>32,'country_id'=>1,'name'=>'النزهة الجديدة'],
            ['id'=>33,'country_id'=>1,'name'=>'الموسكى'],
            ['id'=>34,'country_id'=>1,'name'=>'المنيل'],
            ['id'=>35,'country_id'=>1,'name'=>'المقطم'],
            ['id'=>36,'country_id'=>1,'name'=>'المعصرة'],
            ['id'=>37,'country_id'=>1,'name'=>'المعادى'],
            ['id'=>38,'country_id'=>1,'name'=>'المطرية'],
            ['id'=>39,'country_id'=>1,'name'=>'المرج'],
            ['id'=>40,'country_id'=>1,'name'=>'الماظة'],
            ['id'=>41,'country_id'=>1,'name'=>'القطامية'],
            ['id'=>42,'country_id'=>1,'name'=>'القاهرة الجديدة'],
            ['id'=>43,'country_id'=>1,'name'=>'الفسطاط'],
            ['id'=>44,'country_id'=>1,'name'=>'العتبة'],
            ['id'=>45,'country_id'=>1,'name'=>'العبور'],
            ['id'=>46,'country_id'=>1,'name'=>'العباسية'],
            ['id'=>47,'country_id'=>1,'name'=>'العاصمة الادارية الجديدة'],
            ['id'=>48,'country_id'=>1,'name'=>'الشرابية'],
            ['id'=>49,'country_id'=>1,'name'=>'السيدة زينب'],
            ['id'=>50,'country_id'=>1,'name'=>'الزمالك'],
            ['id'=>51,'country_id'=>1,'name'=>'الزاوية الحمراء'],
            ['id'=>52,'country_id'=>1,'name'=>'الدرب الاحمر'],
            ['id'=>53,'country_id'=>1,'name'=>'الدراسة'],
            ['id'=>54,'country_id'=>1,'name'=>'الحلمية الجديدة'],
            ['id'=>55,'country_id'=>1,'name'=>'الجمالية'],
            ['id'=>56,'country_id'=>1,'name'=>'التبين'],
            ['id'=>57,'country_id'=>1,'name'=>'البساتين'],
            ['id'=>58,'country_id'=>1,'name'=>'الاميرية'],
            ['id'=>59,'country_id'=>2,'name'=>'6 اكتوبر'],
            ['id'=>60,'country_id'=>2,'name'=>'ابو رواش'],
            ['id'=>61,'country_id'=>2,'name'=>'ارض اللواء'],
            ['id'=>62,'country_id'=>2,'name'=>'البدرشين'],
            ['id'=>63,'country_id'=>2,'name'=>'البراجيل'],
            ['id'=>64,'country_id'=>2,'name'=>'الحوامدية'],
            ['id'=>65,'country_id'=>2,'name'=>'الدقى '],
            ['id'=>66,'country_id'=>2,'name'=>'الشيخ زايد'],
            ['id'=>67,'country_id'=>2,'name'=>'الصف'],
            ['id'=>68,'country_id'=>2,'name'=>'العجوزة'],
            ['id'=>69,'country_id'=>2,'name'=>'العياط'],
            ['id'=>70,'country_id'=>2,'name'=>'الكيت كات'],
            ['id'=>71,'country_id'=>2,'name'=>'المنصورية'],
            ['id'=>72,'country_id'=>2,'name'=>'المنيب'],
            ['id'=>73,'country_id'=>2,'name'=>'المهندسين'],
            ['id'=>74,'country_id'=>2,'name'=>'الهرم'],
            ['id'=>75,'country_id'=>2,'name'=>'الوراق'],
            ['id'=>76,'country_id'=>2,'name'=>'امبابة'],
            ['id'=>77,'country_id'=>2,'name'=>'اوسيم'],
            ['id'=>78,'country_id'=>2,'name'=>'ابو النمرس'],
            ['id'=>79,'country_id'=>2,'name'=>'بشتيل'],
            ['id'=>80,'country_id'=>2,'name'=>'بولاق الدكرور'],
            ['id'=>81,'country_id'=>2,'name'=>'ترسا'],
            ['id'=>82,'country_id'=>2,'name'=>'جزيرة الدهب'],
            ['id'=>83,'country_id'=>2,'name'=>'حدائق اكتوبر'],
            ['id'=>84,'country_id'=>2,'name'=>'حدائق الاهرام'],
            ['id'=>85,'country_id'=>2,'name'=>'حى الجيزة'],
            ['id'=>86,'country_id'=>2,'name'=>'دهشور'],
            ['id'=>87,'country_id'=>2,'name'=>'صفط اللبن'],
            ['id'=>88,'country_id'=>2,'name'=>'فيصل'],
            ['id'=>90,'country_id'=>2,'name'=>'كرداسة'],
            ['id'=>91,'country_id'=>2,'name'=>'مركز الجيزة'],
            ['id'=>92,'country_id'=>2,'name'=>'مريوطية'],
            ['id'=>93,'country_id'=>2,'name'=>'منيل شيحة'],
            ['id'=>94,'country_id'=>2,'name'=>'ناهيا'],
            ['id'=>95,'country_id'=>3,'name'=>'ابو تلات'],
            ['id'=>96,'country_id'=>3,'name'=>'ابوقير'],
            ['id'=>97,'country_id'=>3,'name'=>'الابراهيمية'],
            ['id'=>98,'country_id'=>3,'name'=>'الازاريطة'],
            ['id'=>89,'country_id'=>3,'name'=>'الجمرك'],
            ['id'=>99,'country_id'=>3,'name'=>'الحضرة'],
            ['id'=>100,'country_id'=>3,'name'=>'الدخيلة'],
            ['id'=>101,'country_id'=>3,'name'=>'السيوف'],
            ['id'=>102,'country_id'=>3,'name'=>'الصالحية'],
            ['id'=>103,'country_id'=>3,'name'=>'الظاهرية'],
            ['id'=>104,'country_id'=>3,'name'=>'العامرية'],
            ['id'=>105,'country_id'=>3,'name'=>'العصافرة'],
            ['id'=>106,'country_id'=>3,'name'=>'العطارين'],
            ['id'=>107,'country_id'=>3,'name'=>'العوايد'],
            ['id'=>108,'country_id'=>3,'name'=>'القبارى'],
            ['id'=>109,'country_id'=>3,'name'=>'اللبان'],
            ['id'=>110,'country_id'=>3,'name'=>'المعمورة'],
            ['id'=>111,'country_id'=>3,'name'=>'المكس'],
            ['id'=>112,'country_id'=>3,'name'=>'المنتزه'],
            ['id'=>113,'country_id'=>3,'name'=>'المندرة'],
            ['id'=>114,'country_id'=>3,'name'=>'المنشية'],
            ['id'=>115,'country_id'=>3,'name'=>'النخيل'],
            ['id'=>116,'country_id'=>3,'name'=>'الورديان'],
            ['id'=>117,'country_id'=>3,'name'=>'باكوس'],
            ['id'=>118,'country_id'=>3,'name'=>'بحرى والانفوشى'],
            ['id'=>119,'country_id'=>3,'name'=>'برج العرب'],
            ['id'=>120,'country_id'=>3,'name'=>'بولكلى'],
            ['id'=>121,'country_id'=>3,'name'=>'جليم'],
            ['id'=>122,'country_id'=>3,'name'=>'جناكليس'],
            ['id'=>123,'country_id'=>3,'name'=>'رأس التين'],
            ['id'=>124,'country_id'=>3,'name'=>'رشدى'],
            ['id'=>125,'country_id'=>3,'name'=>'زيزنيا'],
            ['id'=>126,'country_id'=>3,'name'=>'سابا باشا'],
            ['id'=>127,'country_id'=>3,'name'=>'سان ستيفانو'],
            ['id'=>128,'country_id'=>3,'name'=>'سبورتنج'],
            ['id'=>129,'country_id'=>3,'name'=>'ستانلى'],
            ['id'=>130,'country_id'=>3,'name'=>'سموحة'],
            ['id'=>131,'country_id'=>3,'name'=>'سيدى بشر'],
            ['id'=>132,'country_id'=>3,'name'=>'سيدى جابر'],
            ['id'=>133,'country_id'=>3,'name'=>'شاطبى'],
            ['id'=>134,'country_id'=>3,'name'=>'شدس'],
            ['id'=>135,'country_id'=>3,'name'=>'عجمى'],
            ['id'=>136,'country_id'=>3,'name'=>'فلمنج'],
            ['id'=>137,'country_id'=>3,'name'=>'فيكتوريا'],
            ['id'=>138,'country_id'=>3,'name'=>'كامب شيزار'],
            ['id'=>139,'country_id'=>3,'name'=>'كرموز'],
            ['id'=>140,'country_id'=>3,'name'=>'كفر عبدو'],
            ['id'=>141,'country_id'=>3,'name'=>'كليوباترا'],
            ['id'=>142,'country_id'=>3,'name'=>'كوم الدكة'],
            ['id'=>143,'country_id'=>3,'name'=>'كينج مريوط'],
            ['id'=>144,'country_id'=>3,'name'=>'لوران'],
            ['id'=>145,'country_id'=>3,'name'=>'محرم بيك'],
            ['id'=>146,'country_id'=>3,'name'=>'محطة الرمل'],
            ['id'=>147,'country_id'=>3,'name'=>'ميامى'],
            ['id'=>148,'country_id'=>3,'name'=>'مينا البصل'],
            ['id'=>149,'country_id'=>4,'name'=>'ابوصوير'],
            ['id'=>150,'country_id'=>4,'name'=>'التل الكبير'],
            ['id'=>151,'country_id'=>4,'name'=>'القصاصين'],
            ['id'=>152,'country_id'=>4,'name'=>'القنطرة شرق'],
            ['id'=>153,'country_id'=>4,'name'=>'القنطرة غرب'],
            ['id'=>154,'country_id'=>4,'name'=>'فايد'],
            ['id'=>155,'country_id'=>4,'name'=>'مدينة الاسماعيلية'],
            ['id'=>156,'country_id'=>7,'name'=>'أرمنت'],
            ['id'=>157,'country_id'=>7,'name'=>'اسنا'],
            ['id'=>158,'country_id'=>7,'name'=>'البياضية'],
            ['id'=>159,'country_id'=>7,'name'=>'الزينية'],
            ['id'=>160,'country_id'=>7,'name'=>'الطود'],
            ['id'=>161,'country_id'=>7,'name'=>'القرنه'],
            ['id'=>162,'country_id'=>7,'name'=>'مدينة الاقصر'],
            ['id'=>163,'country_id'=>11,'name'=>'الجونة'],
            ['id'=>164,'country_id'=>11,'name'=>'الغردقة'],
            ['id'=>165,'country_id'=>11,'name'=>'القصير'],
            ['id'=>166,'country_id'=>11,'name'=>'حلايب وشلاتين'],
            ['id'=>167,'country_id'=>11,'name'=>'راس سوما'],
            ['id'=>168,'country_id'=>11,'name'=>'راس غارب'],
            ['id'=>169,'country_id'=>11,'name'=>'سفاجا'],
            ['id'=>170,'country_id'=>11,'name'=>'سهل حشيش'],
            ['id'=>171,'country_id'=>11,'name'=>'سوما باى'],
            ['id'=>172,'country_id'=>11,'name'=>'مرسى علم'],
            ['id'=>173,'country_id'=>11,'name'=>'مكادى باى'],
            ['id'=>174,'country_id'=>10,'name'=>'ابوالمطامير'],
            ['id'=>175,'country_id'=>10,'name'=>'ابوحمص'],
            ['id'=>176,'country_id'=>10,'name'=>'ادكو'],
            ['id'=>177,'country_id'=>10,'name'=>'الدلنجات'],
            ['id'=>178,'country_id'=>10,'name'=>'الرحمانية'],
            ['id'=>179,'country_id'=>10,'name'=>'المحمودية'],
            ['id'=>180,'country_id'=>10,'name'=>'النوبارية'],
            ['id'=>181,'country_id'=>10,'name'=>'النوبارية الجديدة'],
            ['id'=>182,'country_id'=>10,'name'=>'ايتاى البارود'],
            ['id'=>183,'country_id'=>10,'name'=>'حوش عيسى'],
            ['id'=>184,'country_id'=>10,'name'=>'دمنهور'],
            ['id'=>185,'country_id'=>10,'name'=>'رشيد'],
            ['id'=>186,'country_id'=>10,'name'=>'شبراخيت'],
            ['id'=>187,'country_id'=>10,'name'=>'كفر الدوار'],
            ['id'=>188,'country_id'=>10,'name'=>'كوم حمادة'],
            ['id'=>189,'country_id'=>10,'name'=>'مركز بدر'],
            ['id'=>190,'country_id'=>10,'name'=>'وادى النطرون'],
            ['id'=>191,'country_id'=>15,'name'=>'اجا'],
            ['id'=>192,'country_id'=>15,'name'=>'اخطاب'],
            ['id'=>193,'country_id'=>15,'name'=>'السنبلاوين'],
            ['id'=>194,'country_id'=>15,'name'=>'الكردى'],
            ['id'=>195,'country_id'=>15,'name'=>'المنزلة'],
            ['id'=>196,'country_id'=>15,'name'=>'المنصورة'],
            ['id'=>197,'country_id'=>15,'name'=>'المنصورة الجديدة'],
            ['id'=>198,'country_id'=>15,'name'=>'بلقاس'],
            ['id'=>199,'country_id'=>15,'name'=>'بنى عبيد'],
            ['id'=>200,'country_id'=>15,'name'=>'تمى المديد'],
            ['id'=>201,'country_id'=>15,'name'=>'جمصه'],
            ['id'=>202,'country_id'=>15,'name'=>'دكرنس'],
            ['id'=>203,'country_id'=>15,'name'=>'شربين'],
            ['id'=>204,'country_id'=>15,'name'=>'طلخا'],
            ['id'=>205,'country_id'=>15,'name'=>'مركز الجمالية'],
            ['id'=>206,'country_id'=>15,'name'=>'مركز المطرية'],
            ['id'=>207,'country_id'=>15,'name'=>'منية النصر'],
            ['id'=>208,'country_id'=>15,'name'=>'ميت سلسيل'],
            ['id'=>209,'country_id'=>15,'name'=>'ميت غمر'],
            ['id'=>210,'country_id'=>15,'name'=>'نبروه'],
            ['id'=>211,'country_id'=>27,'name'=>'العين السخنة'],
            ['id'=>212,'country_id'=>27,'name'=>'حى الاربعين'],
            ['id'=>213,'country_id'=>27,'name'=>'حى الجناين'],
            ['id'=>214,'country_id'=>27,'name'=>'حى السويس'],
            ['id'=>215,'country_id'=>27,'name'=>'حى عتاقة'],
            ['id'=>216,'country_id'=>27,'name'=>'حى فيصل'],
            ['id'=>217,'country_id'=>17,'name'=>'ابوحماد'],
            ['id'=>218,'country_id'=>17,'name'=>'ابوكبير'],
            ['id'=>219,'country_id'=>17,'name'=>'الابراهيمية'],
            ['id'=>220,'country_id'=>17,'name'=>'الحسينية'],
            ['id'=>221,'country_id'=>17,'name'=>'الزقازيق'],
            ['id'=>222,'country_id'=>17,'name'=>'الصالحية الجديدة'],
            ['id'=>223,'country_id'=>17,'name'=>'العاشر من رمضان'],
            ['id'=>224,'country_id'=>17,'name'=>'القرين'],
            ['id'=>225,'country_id'=>17,'name'=>'القنايات'],
            ['id'=>226,'country_id'=>17,'name'=>'اولاد صقر'],
            ['id'=>227,'country_id'=>17,'name'=>'بلبيس'],
            ['id'=>228,'country_id'=>17,'name'=>'ديرب نجم'],
            ['id'=>229,'country_id'=>17,'name'=>'فاقوس'],
            ['id'=>230,'country_id'=>17,'name'=>'كفر صقر'],
            ['id'=>231,'country_id'=>17,'name'=>'مشتول السوق'],
            ['id'=>232,'country_id'=>17,'name'=>'منيا القمح'],
            ['id'=>233,'country_id'=>17,'name'=>'ههيا'],
            ['id'=>234,'country_id'=>19,'name'=>'السنطة'],
            ['id'=>235,'country_id'=>19,'name'=>'المحلة الكبرى'],
            ['id'=>236,'country_id'=>19,'name'=>'بسيون'],
            ['id'=>237,'country_id'=>19,'name'=>'زفتى'],
            ['id'=>238,'country_id'=>19,'name'=>'سمنود'],
            ['id'=>239,'country_id'=>19,'name'=>'طنطا'],
            ['id'=>240,'country_id'=>19,'name'=>'قطور'],
            ['id'=>241,'country_id'=>19,'name'=>'كفر الزيات'],
            ['id'=>242,'country_id'=>20,'name'=>'ابشواى'],
            ['id'=>243,'country_id'=>20,'name'=>'اطسا'],
            ['id'=>244,'country_id'=>20,'name'=>'الفيوم الجديدة'],
            ['id'=>245,'country_id'=>20,'name'=>'سنورس'],
            ['id'=>246,'country_id'=>20,'name'=>'طامية'],
            ['id'=>247,'country_id'=>20,'name'=>'مدينة الفيوم'],
            ['id'=>248,'country_id'=>20,'name'=>'يوسف الصديق'],
            ['id'=>249,'country_id'=>21,'name'=>'الخانكة'],
            ['id'=>250,'country_id'=>21,'name'=>'الخصوص'],
            ['id'=>251,'country_id'=>21,'name'=>'القناطر الخيرية'],
            ['id'=>252,'country_id'=>21,'name'=>'بنها'],
            ['id'=>253,'country_id'=>21,'name'=>'بهتيم'],
            ['id'=>254,'country_id'=>21,'name'=>'شبرا الخيمة'],
            ['id'=>255,'country_id'=>21,'name'=>'شبين القناطر'],
            ['id'=>256,'country_id'=>21,'name'=>'طوخ'],
            ['id'=>257,'country_id'=>21,'name'=>'قليوب'],
            ['id'=>258,'country_id'=>21,'name'=>'قها'],
            ['id'=>259,'country_id'=>21,'name'=>'كفر شكر'],
            ['id'=>260,'country_id'=>21,'name'=>'مسطرد'],
            ['id'=>261,'country_id'=>24,'name'=>'اشمون'],
            ['id'=>262,'country_id'=>24,'name'=>'الباجور'],
            ['id'=>263,'country_id'=>24,'name'=>'السادات'],
            ['id'=>264,'country_id'=>24,'name'=>'الشهداء'],
            ['id'=>265,'country_id'=>24,'name'=>'بركة السبع'],
            ['id'=>266,'country_id'=>24,'name'=>'تلا'],
            ['id'=>267,'country_id'=>24,'name'=>'سرس الليان'],
            ['id'=>268,'country_id'=>24,'name'=>'شبين الكوم'],
            ['id'=>269,'country_id'=>24,'name'=>'قويسنا'],
            ['id'=>270,'country_id'=>24,'name'=>'منوف'],
            ['id'=>271,'country_id'=>28,'name'=>'ابو قرقاص'],
            ['id'=>272,'country_id'=>28,'name'=>'العدوة'],
            ['id'=>273,'country_id'=>28,'name'=>'مدينة المنيا'],
            ['id'=>274,'country_id'=>28,'name'=>'المنيا الجديدة'],
            ['id'=>275,'country_id'=>28,'name'=>'بنى مزار'],
            ['id'=>276,'country_id'=>28,'name'=>'دير مواس'],
            ['id'=>277,'country_id'=>28,'name'=>'سمالوط'],
            ['id'=>278,'country_id'=>28,'name'=>'مطاى'],
            ['id'=>279,'country_id'=>28,'name'=>'مغاغا'],
            ['id'=>280,'country_id'=>28,'name'=>'ملوى'],
            ['id'=>281,'country_id'=>25,'name'=>'الخارجة'],
            ['id'=>282,'country_id'=>25,'name'=>'الداخلة'],
            ['id'=>283,'country_id'=>25,'name'=>'الفرافرة'],
            ['id'=>284,'country_id'=>25,'name'=>'باريس'],
            ['id'=>285,'country_id'=>25,'name'=>'بلاط'],
            ['id'=>286,'country_id'=>25,'name'=>'مدينة موط'],
            ['id'=>287,'country_id'=>12,'name'=>'مدينة بنى سويف'],
            ['id'=>288,'country_id'=>12,'name'=>'بنى سويف الجديدة'],
            ['id'=>289,'country_id'=>12,'name'=>'الفشن'],
            ['id'=>290,'country_id'=>12,'name'=>'الواسطى'],
            ['id'=>291,'country_id'=>12,'name'=>'اهناسيا'],
            ['id'=>292,'country_id'=>12,'name'=>'ببا'],
            ['id'=>293,'country_id'=>12,'name'=>'سمسطا'],
            ['id'=>294,'country_id'=>12,'name'=>'ناصر'],
            ['id'=>295,'country_id'=>13,'name'=>'حى الجنوب'],
            ['id'=>296,'country_id'=>13,'name'=>'حى الزهور'],
            ['id'=>297,'country_id'=>13,'name'=>'حى الشرق'],
            ['id'=>298,'country_id'=>13,'name'=>'حى الضواحى'],
            ['id'=>299,'country_id'=>13,'name'=>'حى العرب'],
            ['id'=>300,'country_id'=>13,'name'=>'حى المناخ'],
            ['id'=>301,'country_id'=>13,'name'=>'مدينة بور فؤاد'],
            ['id'=>302,'country_id'=>14,'name'=>'ابو رديس'],
            ['id'=>303,'country_id'=>14,'name'=>'ابو زنيمة'],
            ['id'=>304,'country_id'=>14,'name'=>'دهب'],
            ['id'=>305,'country_id'=>14,'name'=>'راس سدر'],
            ['id'=>306,'country_id'=>14,'name'=>'سانت كاترين'],
            ['id'=>307,'country_id'=>14,'name'=>'شرم الشيخ'],
            ['id'=>308,'country_id'=>14,'name'=>'طابا'],
            ['id'=>309,'country_id'=>14,'name'=>'طور سيناء'],
            ['id'=>310,'country_id'=>14,'name'=>'نويبع'],
            ['id'=>311,'country_id'=>16,'name'=>'مدينة دمياط'],
            ['id'=>312,'country_id'=>16,'name'=>'دمياط الجديدة'],
            ['id'=>313,'country_id'=>16,'name'=>'الزرقا'],
            ['id'=>314,'country_id'=>16,'name'=>'السرو'],
            ['id'=>315,'country_id'=>16,'name'=>'راس البر'],
            ['id'=>316,'country_id'=>16,'name'=>'عزبة البرج'],
            ['id'=>317,'country_id'=>16,'name'=>'فارسكور'],
            ['id'=>318,'country_id'=>16,'name'=>'كفر البطيخ'],
            ['id'=>319,'country_id'=>16,'name'=>'كفر سعد'],
            ['id'=>320,'country_id'=>16,'name'=>'مركز الروضة'],
            ['id'=>321,'country_id'=>16,'name'=>'ميت ابوغالب'],
            ['id'=>322,'country_id'=>8,'name'=>'مدينة سوهاج'],
            ['id'=>323,'country_id'=>8,'name'=>'سوهاج الجديدة'],
            ['id'=>324,'country_id'=>8,'name'=>'اخميم'],
            ['id'=>325,'country_id'=>8,'name'=>'البلينا'],
            ['id'=>326,'country_id'=>8,'name'=>'العسيرات'],
            ['id'=>327,'country_id'=>8,'name'=>'المراغة'],
            ['id'=>328,'country_id'=>8,'name'=>'المنشاة'],
            ['id'=>329,'country_id'=>8,'name'=>'جرجا'],
            ['id'=>330,'country_id'=>8,'name'=>'ساقلتة'],
            ['id'=>331,'country_id'=>8,'name'=>'طما'],
            ['id'=>332,'country_id'=>8,'name'=>'طهطا'],
            ['id'=>333,'country_id'=>8,'name'=>'جهينة'],
            ['id'=>334,'country_id'=>8,'name'=>'دار السلام'],
            ['id'=>335,'country_id'=>9,'name'=>'مدينة قنا'],
            ['id'=>336,'country_id'=>9,'name'=>'ابوتشت'],
            ['id'=>337,'country_id'=>9,'name'=>'الوقف'],
            ['id'=>338,'country_id'=>9,'name'=>'دشنا'],
            ['id'=>339,'country_id'=>9,'name'=>'فرشوط'],
            ['id'=>340,'country_id'=>9,'name'=>'قفط'],
            ['id'=>341,'country_id'=>9,'name'=>'قوص'],
            ['id'=>342,'country_id'=>9,'name'=>'نجع حمادى'],
            ['id'=>343,'country_id'=>9,'name'=>'نقادة'],
            ['id'=>344,'country_id'=>22,'name'=>'مدينة كفر الشيخ'],
            ['id'=>345,'country_id'=>22,'name'=>'البرلس'],
            ['id'=>346,'country_id'=>22,'name'=>'الحامول'],
            ['id'=>347,'country_id'=>22,'name'=>'الرياض'],
            ['id'=>348,'country_id'=>22,'name'=>'بلطيم'],
            ['id'=>349,'country_id'=>22,'name'=>'بيلا'],
            ['id'=>350,'country_id'=>22,'name'=>'دسوق'],
            ['id'=>351,'country_id'=>22,'name'=>'سيدى سالم'],
            ['id'=>352,'country_id'=>22,'name'=>'فوه'],
            ['id'=>353,'country_id'=>22,'name'=>'قلين'],
            ['id'=>354,'country_id'=>22,'name'=>'مطوبس'],
            ['id'=>355,'country_id'=>23,'name'=>'مرسى مطروح'],
            ['id'=>356,'country_id'=>23,'name'=>'الحمام'],
            ['id'=>357,'country_id'=>23,'name'=>'الساحل الشمالى'],
            ['id'=>358,'country_id'=>23,'name'=>'السلوم'],
            ['id'=>359,'country_id'=>23,'name'=>'الضبعة'],
            ['id'=>360,'country_id'=>23,'name'=>'العلمين'],
            ['id'=>361,'country_id'=>23,'name'=>'النجيلة'],
            ['id'=>362,'country_id'=>23,'name'=>'برانى'],
            ['id'=>363,'country_id'=>23,'name'=>'سيوة'],
        ];
        State::insert($statiesRecords);
    }
}
